export const favoritePlayersNames = [
  "Ousmane Dembélé",
  "Lamine Yamal",
  "Raphinha",
  "Vitinha",
  "Mohamed Salah",
  "Joao Neves",
  "Achraf Hakimi",
  "Pedri",
  "Robert Lewandowski",
  "Nuno Mendes",
  "Harry Kane",
  "Joshua Kimmich",
  "Virgil Van Dijk",
  "Kylian Mbappé",
  "Serhou Guirassy",
  "Bruno Fernandes",
  "William Saliba",
  "Yan Sommer",
  "Lautaro Martínez",
  "Jude Bellingham",
  // 21 à 50
  "Vinicius Jr",
  "Nicolo Barella",
  "Jamal Musiala",
  "Phil Foden",
  "Rodri",
  "Bukayo Saka",
  "Martin Ødegaard",
  "Frenkie de Jong",
  "Khvicha Kvaratskhelia",
  "Marcus Rashford",
  "Rafael Leão",
  "Bernardo Silva",
  "Eduardo Camavinga",
  "Federico Valverde",
  "Antoine Griezmann",
  "Victor Osimhen",
  "Mike Maignan",
  "Gianluigi Donnarumma",
  "Gabriel Martinelli",
  "Declan Rice",
  "Josko Gvardiol",
  "Marquinhos",
  "Sandro Tonali",
  "Christopher Nkunku",
  "Mason Mount",
  "Romelu Lukaku",
  "Leroy Sané",
  "Giovanni Di Lorenzo",
  "Alejandro Balde"
]; 